spring:
  application:
    name: eureka-server
  profiles:
    active: dev
  config:
    import: "optional:configserver:${CONFIG_SERVER_URL}:${CONFIG_SERVER_PORT}"

server:
  port: 8070

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 30
    leaseExpirationDurationInSeconds: 90
  server:
    renewalPercentThreshold: 0.85