spring:
  application:
    name: gateway-server
  profiles:
    active: dev
  config:
    import: "optional:configserver:${CONFIG_SERVER_URL}:${CONFIG_SERVER_PORT}"
server:
  port: 8072
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#  endpoint:
#    gateway:
#      enabled: true
