apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
        - name: database
          image: postgres:latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "postgres"
            - name: POSTGRES_DB
              value: "postgres"
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
            - name: db-scripts
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-pvc
        - name: db-scripts
          configMap:
            name: db-scripts-config
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: db-scripts-config
data:
# Add your db scripts here as key-value pairs
# example.sql: |
#   CREATE TABLE example (...);
---
apiVersion: v1
kind: Service
metadata:
  name: database
spec:
  ports:
    - port: 5432
  selector:
    app: database
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: database-headless
  labels:
    app: database
spec:
  ports:
    - port: 5432
      protocol: TCP
  clusterIP: None
  selector:
    app: database
