apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka-server
  template:
    metadata:
      labels:
        app: eureka-server
    spec:
      containers:
        - name: eureka-server
          image: your-eureka-server-image
          ports:
            - containerPort: 8070
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
            - name: CONFIG_SERVER_URL
              value: http://config-server
            - name: CONFIG_SERVER_PORT
              value: "8071"
      volumes:
        - name: fluentd-socket
          hostPath:
            path: /var/run/fluentd.sock
      volumeMounts:
        - name: fluentd-socket
          mountPath: /var/run/fluentd.sock
---
apiVersion: v1
kind: Service
metadata:
  name: eureka-server
spec:
  ports:
    - port: 8070
      targetPort: 8070
  selector:
    app: eureka-server
