apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-server
  template:
    metadata:
      labels:
        app: gateway-server
    spec:
      containers:
        - name: gateway-server
          image: your-gateway-server-image
          ports:
            - containerPort: 8072
          env:
            - name: SPRING_CLOUD_CONFIG_URI
              value: http://config-server:8071
            - name: SPRING_PROFILES_ACTIVE
              value: prod
      volumes:
        - name: fluentd-socket
          hostPath:
            path: /var/run/fluentd.sock
      volumeMounts:
        - name: fluentd-socket
          mountPath: /var/run/fluentd.sock
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-server
spec:
  ports:
    - port: 8072
      targetPort: 8072
  selector:
    app: gateway-server
