apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault
  template:
    metadata:
      labels:
        app: vault
    spec:
      containers:
        - name: vault
          image: hashicorp/vault:latest
          ports:
            - containerPort: 8200
          env:
            - name: VAULT_ADDR
              value: http://127.0.0.1:8200
          volumeMounts:
            - name: vault-config
              mountPath: /vault/config
            - name: vault-data
              mountPath: /vault/data
      volumes:
        - name: vault-config
          persistentVolumeClaim:
            claimName: vault-config-pvc
        - name: vault-data
          persistentVolumeClaim:
            claimName: vault-data-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vault-config-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vault-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: vault
spec:
  ports:
    - port: 8200
      targetPort: 8200
  selector:
    app: vault
