spring:
  application.name: config-server
  profiles.active: vault, git
  cloud:
    config.server:
        vault:
          kv-version: 2
          authentication: TOKEN
          token: ${VAULT_TOKEN}
          order: 1
          profile-separator: "-"
        git:
          uri: git@github.com:vnsemkin/Microservices.git
          search-paths: config/microservices
          default-label: master
          order: 2
server.port: 8071

