spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        git:
          uri: git@github.com:vnsemkin/Microservices.git
          search-paths: config
      #        native:
      #            search-locations: classpath:/config
server:
  port: 8071